### ISSUE TITLE
Error: undefined symbol

### ISSUE THREAD

**Issue by edb2018** [Stovent/Lua-GPIO#1]
Installed as instructed and copied example into file LDR2.lua. When run I get following error:
$ lua LDR2.lua
lua: LDR2.lua:2: /usr/local/lib/libLua-GPIO.so: undefined symbol: luaL_setfuncs
stack traceback:
	[C]: in function 'assert'
	LDR2.lua:2: in main chunk
	[C]: ?

Using Raspberry pi 3B with "Raspbian GNU/Linux 10 (buster)"
What did I do wrong?

**Comment by Stovent** [comment]
Which version of Lua is installed?

**Comment by edb2018** [comment]
Just found that I'm still on Lua 5.1.5. That explains it. Thanks anyway for the response.
